name: ci-mac

on: [push]

jobs:
  bootstrap:
    name: Bootstap on macOS using bootstrap.sh
    runs-on: macOS-latest
    steps:
      - run: curl -sf https://raw.githubusercontent.com/nothink-sbinc/dotfiles/master/mac_bootstrap.sh | sh -s
